# Generated by Django 4.1.2 on 2022-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='逝者名字')),
                ('birth', models.CharField(max_length=100, verbose_name='出生日期')),
                ('passDate', models.CharField(max_length=100, verbose_name='逝世日期')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('desc', models.TextField(max_length=300, verbose_name='介绍文字')),
            ],
        ),
    ]
